name: Rollback Production

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo "Rollback workflow registered successfully"